# Generated by Django 5.0.4 on 2024-06-19 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('idCargo', models.IntegerField(db_column='codCargo', primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('fCreacion', models.DateTimeField(auto_now_add=True)),
                ('nombreCargo', models.CharField(choices=[('Usuario', 'Usuario normal'), ('EncargadoHabitacion', 'Encargado de Habitaciones'), ('EncargadoInventario', 'Encargado de Inventario'), ('EncargadoServAdicional', 'Encargado de Servicios Adicionales'), ('EncargadoReserva', 'Encargado de Reservas'), ('EncargadoMantencion', 'Encargado de Mantención'), ('EncargadoFinanzas', 'Encargado de Finanzas'), ('EncargadoCliente', 'Encargado de Clientes'), ('EncargadoRestaurante', 'Encargado de Restaurante'), ('EncargadoBar', 'Encargado de Bar'), ('EncargadoSpa', 'Encargado de Spa'), ('EncargadoPiscina', 'Encargado de Piscina'), ('EncargadoGimnasio', 'Encargado de Gimnasio'), ('EncargadoSalonEventos', 'Encargado de Salón de Eventos'), ('EncargadoTienda', 'Encargado de Tienda'), ('EncargadoCocina', 'Encargado de Cocina'), ('EncargadoLavanderia', 'Encargado de Lavandería'), ('EncargadoRecepcion', 'Encargado de Recepción'), ('EncargadoSeguridad', 'Encargado de Seguridad'), ('EncargadoMascotas', 'Encargado de Mascotas'), ('EncargadoJardineria', 'Encargado de Jardinería'), ('EncargadoAseo', 'Encargado de Aseo'), ('EncargadoMensajeria', 'Encargado de Mensajería'), ('EncargadoEstacionamiento', 'Encargado de Estacionamiento'), ('EncargadoMantVehiculos', 'Encargado de Mantención de Vehículos'), ('EncargadoMantMaquinaria', 'Encargado de Mantención de Maquinaria'), ('EncargadoMantEquipos', 'Encargado de Mantención de Equipos'), ('EncargadoMantInfraestructura', 'Encargado de Mantención de Infraestructura'), ('EncargadoMantTecnologia', 'Encargado de Mantención de Tecnología'), ('EncargadoMantRedes', 'Encargado de Mantención de Redes'), ('EncargadoMantSistemas', 'Encargado de Mantención de')], default='Usuario', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('categorias', models.CharField(choices=[('Vip', 'Vip'), ('Normal', 'Normal'), ('Economico', 'Economico'), ('Familiar', 'Familiar'), ('Suite', 'Suite'), ('Presidencial', 'Presidencial')], default='Normal', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('idFPago', models.IntegerField(db_column='codFormaPago', primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(db_column='descripcion', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('idGenero', models.AutoField(db_column='id_genero', primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(db_column='genero', max_length=20)),
                ('fCreacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_provincia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroServicioAdicional',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('servicios_ad', models.CharField(choices=[('Wifi', 'Wifi'), ('Tv', 'Tv'), ('Desayuno', 'Desayuno'), ('Almuerzo', 'Almuerzo'), ('Cena', 'Cena'), ('Estacionamiento', 'Estacionamiento'), ('Piscina', 'Piscina'), ('Gimnasio', 'Gimnasio'), ('Spa', 'Spa'), ('Bar', 'Bar'), ('Restaurante', 'Restaurante'), ('Mascotas', 'Mascotas'), ('Jardineria', 'Jardineria'), ('Aseo', 'Aseo'), ('Mensajeria', 'Mensajeria'), ('SalonEventos', 'Salon de Eventos'), ('Cocina', 'Cocina'), ('Lavanderia', 'Lavanderia'), ('Estacionamiento', 'Estacionamiento')], default='Wifi', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id_hotel', models.AutoField(primary_key=True, serialize=False)),
                ('patente_hotel', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=50)),
                ('total_habitaciones_hotel', models.IntegerField()),
                ('estado_habitacion', models.BooleanField()),
                ('id_comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False)),
                ('dv', models.CharField(max_length=1)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('apPaterno', models.CharField(blank=True, max_length=30, null=True)),
                ('apMaterno', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('fechaNacimiento', models.DateField(auto_now_add=True, db_column='fecha_nacimiento', null=True)),
                ('fCreacion', models.DateTimeField(auto_now_add=True)),
                ('telefono', models.CharField(max_length=15)),
                ('comuna', models.ForeignKey(db_column='id_comuna', on_delete=django.db.models.deletion.DO_NOTHING, to='core.comuna')),
                ('genero', models.ForeignKey(db_column='id_genero', on_delete=django.db.models.deletion.DO_NOTHING, to='core.genero')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idEmpleado', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=20)),
                ('clave', models.CharField(max_length=10)),
                ('sueldo', models.IntegerField()),
                ('fCreacion', models.DateTimeField(auto_now_add=True)),
                ('codCargo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.cargo')),
                ('rut', models.ForeignKey(db_column='rut', on_delete=django.db.models.deletion.DO_NOTHING, to='core.persona')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='id_provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.provincia'),
        ),
        migrations.AddField(
            model_name='provincia',
            name='id_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.region'),
        ),
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id_tipo_habitacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('tipos_habitaciones', models.CharField(choices=[('Simple', 'Simple'), ('Doble', 'Doble'), ('Triple', 'Triple'), ('Matrimonial', 'Matrimonial')], default='Simple', max_length=50)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroHabitacion',
            fields=[
                ('id_habitacion', models.AutoField(primary_key=True, serialize=False)),
                ('numero_habitacion', models.IntegerField()),
                ('cant_dormitorios', models.IntegerField()),
                ('cant_banos', models.IntegerField()),
                ('cant_camas', models.IntegerField()),
                ('tamano_camas', models.CharField(max_length=50)),
                ('cant_personas_disp', models.IntegerField()),
                ('descripcion', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('estado_habitacion', models.BooleanField()),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empleado')),
                ('id_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hotel')),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.registroservicioadicional')),
                ('id_tipo_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipohabitacion')),
            ],
        ),
        migrations.CreateModel(
            name='HotelDetalle',
            fields=[
                ('id_hotel_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=350)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
                ('id_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hotel')),
                ('id_registro_servicio_adicional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.registroservicioadicional')),
                ('id_tipo_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipohabitacion')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=20, unique=True)),
                ('clave', models.CharField(max_length=10)),
                ('rut', models.ForeignKey(db_column='rut', on_delete=django.db.models.deletion.DO_NOTHING, to='core.persona')),
            ],
        ),
    ]
