# Generated by Django 5.0.4 on 2024-06-07 01:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('categorias', models.CharField(choices=[('Vip', 'Vip'), ('Normal', 'Normal'), ('Economico', 'Economico'), ('Familiar', 'Familiar'), ('Suite', 'Suite'), ('Presidencial', 'Presidencial')], default='Normal', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_provincia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroServicioAdicional',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('servicios_ad', models.CharField(choices=[('Wifi', 'Wifi'), ('Tv', 'Tv'), ('Desayuno', 'Desayuno'), ('Almuerzo', 'Almuerzo'), ('Cena', 'Cena'), ('Estacionamiento', 'Estacionamiento'), ('Piscina', 'Piscina'), ('Gimnasio', 'Gimnasio'), ('Spa', 'Spa'), ('Bar', 'Bar'), ('Restaurante', 'Restaurante'), ('Mascotas', 'Mascotas'), ('Jardineria', 'Jardineria'), ('Aseo', 'Aseo'), ('Mensajeria', 'Mensajeria'), ('SalonEventos', 'Salon de Eventos'), ('Cocina', 'Cocina'), ('Lavanderia', 'Lavanderia'), ('Estacionamiento', 'Estacionamiento')], default='Wifi', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id_hotel', models.AutoField(primary_key=True, serialize=False)),
                ('patente_hotel', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=50)),
                ('total_habitaciones_hotel', models.IntegerField()),
                ('estado_habitacion', models.BooleanField()),
                ('id_comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comuna')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='id_provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.provincia'),
        ),
        migrations.AddField(
            model_name='provincia',
            name='id_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.region'),
        ),
        migrations.CreateModel(
            name='RegistroCuentaEmpleados',
            fields=[
                ('rut', models.CharField(help_text='Ingrese el RUT sin puntos ni guión', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nombre_usuario', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('ap_paterno', models.CharField(max_length=50)),
                ('ap_materno', models.CharField(max_length=50)),
                ('correo_alternativo', models.EmailField(blank=True, max_length=254, null=True)),
                ('contrasena', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='La contraseña debe tener al menos 8 caracteres, una letra mayúscula, una letra minúscula, un número y un carácter especial.', regex='^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$')])),
                ('telefono', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimo_acceso', models.DateTimeField(auto_now=True)),
                ('roles', models.CharField(choices=[('Usuario', 'Usuario normal'), ('EncargadoHabitacion', 'Encargado de Habitaciones'), ('EncargadoInventario', 'Encargado de Inventario'), ('EncargadoServAdicional', 'Encargado de Servicios Adicionales'), ('EncargadoReserva', 'Encargado de Reservas'), ('EncargadoMantencion', 'Encargado de Mantención'), ('EncargadoFinanzas', 'Encargado de Finanzas'), ('EncargadoCliente', 'Encargado de Clientes'), ('EncargadoRestaurante', 'Encargado de Restaurante'), ('EncargadoBar', 'Encargado de Bar'), ('EncargadoSpa', 'Encargado de Spa'), ('EncargadoPiscina', 'Encargado de Piscina'), ('EncargadoGimnasio', 'Encargado de Gimnasio'), ('EncargadoSalonEventos', 'Encargado de Salón de Eventos'), ('EncargadoTienda', 'Encargado de Tienda'), ('EncargadoCocina', 'Encargado de Cocina'), ('EncargadoLavanderia', 'Encargado de Lavandería'), ('EncargadoRecepcion', 'Encargado de Recepción'), ('EncargadoSeguridad', 'Encargado de Seguridad'), ('EncargadoMascotas', 'Encargado de Mascotas'), ('EncargadoJardineria', 'Encargado de Jardinería'), ('EncargadoAseo', 'Encargado de Aseo'), ('EncargadoMensajeria', 'Encargado de Mensajería'), ('EncargadoEstacionamiento', 'Encargado de Estacionamiento'), ('EncargadoMantVehiculos', 'Encargado de Mantención de Vehículos'), ('EncargadoMantMaquinaria', 'Encargado de Mantención de Maquinaria'), ('EncargadoMantEquipos', 'Encargado de Mantención de Equipos'), ('EncargadoMantInfraestructura', 'Encargado de Mantención de Infraestructura'), ('EncargadoMantTecnologia', 'Encargado de Mantención de Tecnología'), ('EncargadoMantRedes', 'Encargado de Mantención de Redes'), ('EncargadoMantSistemas', 'Encargado de Mantención de')], default='Usuario', max_length=50)),
                ('id_comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroCuentaUsuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('ap_paterno', models.CharField(max_length=50)),
                ('ap_materno', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('contrasena', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=8)),
                ('direccion', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimo_acceso', models.DateTimeField(auto_now=True)),
                ('id_comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id_tipo_habitacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('tipos_habitaciones', models.CharField(choices=[('Simple', 'Simple'), ('Doble', 'Doble'), ('Triple', 'Triple'), ('Matrimonial', 'Matrimonial')], default='Simple', max_length=50)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroHabitacion',
            fields=[
                ('id_habitacion', models.AutoField(primary_key=True, serialize=False)),
                ('numero_habitacion', models.IntegerField()),
                ('cant_dormitorios', models.IntegerField()),
                ('cant_banos', models.IntegerField()),
                ('cant_camas', models.IntegerField()),
                ('tamano_camas', models.CharField(max_length=50)),
                ('cant_personas_disp', models.IntegerField()),
                ('descripcion', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('estado_habitacion', models.BooleanField()),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.registrocuentaempleados')),
                ('id_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hotel')),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.registroservicioadicional')),
                ('id_tipo_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipohabitacion')),
            ],
        ),
    ]
