# Generated by Django 5.0.4 on 2024-06-14 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Usuario'), (2, 'Empleado'), (3, 'Admin')]),
        ),
    ]
