# Generated by Django 5.0.4 on 2024-06-19 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genero',
            name='codigo',
        ),
    ]
