# Generated by Django 5.0.4 on 2024-06-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_genero_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='codigo',
        ),
        migrations.AlterField(
            model_name='cargo',
            name='idCargo',
            field=models.AutoField(db_column='codCargo', primary_key=True, serialize=False),
        ),
    ]
