# Generated by Django 5.0.4 on 2024-06-21 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_cargo_tipocargo_alter_cargo_nombrecargo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroservicioadicional',
            name='servicios_ad',
        ),
        migrations.AddField(
            model_name='registroservicioadicional',
            name='precio',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
