# Generated by Django 5.0.4 on 2024-06-22 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_registroservicioadicional_servicios_ad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('idEvento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fechaInicio', models.DateTimeField()),
                ('fechaTermino', models.DateTimeField()),
                ('descripcion', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('estado', models.BooleanField()),
                ('fCreacion', models.DateTimeField(auto_now_add=True)),
                ('fModificacion', models.DateTimeField(auto_now=True)),
                ('idEmpleado', models.ForeignKey(db_column='idEmpleado', on_delete=django.db.models.deletion.DO_NOTHING, to='core.empleado')),
                ('idFormaPago', models.ForeignKey(db_column='idFormaPago', on_delete=django.db.models.deletion.DO_NOTHING, to='core.formapago')),
                ('idHotel', models.ForeignKey(db_column='idHotel', on_delete=django.db.models.deletion.DO_NOTHING, to='core.hotel')),
                ('idUsuario', models.ForeignKey(db_column='idUsuario', on_delete=django.db.models.deletion.DO_NOTHING, to='core.usuario')),
            ],
        ),
    ]
