# Generated by Django 4.2.13 on 2024-06-24 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_eventos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formapago',
            name='idFPago',
            field=models.AutoField(db_column='codFormaPago', primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('idReserva', models.AutoField(primary_key=True, serialize=False)),
                ('fechaInicio', models.DateTimeField()),
                ('fechaTermino', models.DateTimeField()),
                ('estado', models.BooleanField()),
                ('fCreacion', models.DateTimeField(auto_now_add=True)),
                ('idHabitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.registrohabitacion')),
                ('idHotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hotel')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
    ]
